export const famQuestion = {
    FEACH_QUESTION_AND_ANSWER_IN_API: "FEACH_QUESTION_AND_ANSWER_IN_API",
    UPDATE_QUESTION_AND_ANSWER_DATA: "UPDATE_QUESTION_AND_ANSWER_DATA",

    // UPDATE_ANSWER_BY_ID_IN_REDUCER = "UPDATE_ANSWER_BY_ID_IN_REDUCER",
    // UPDATE_FULL_NAME_VALUE = "UPDATE_FULL_NAME_VALUE",
    // UPDATE_INSTAGRAM_ID_VALUE = "UPDATE_MOBILE_VALUE",

    UPDATE_VALID_MOBILE_VALUE: "UPDATE_VALID_MOBILE_VALUE",
    UPDATE_VALID_FULL_NAME_VALUE: "UPDATE_VALID_FULL_NAME_VALUE",
    UPDATE_VALID_INSTAGRAM_ID: "UPDATE_VALID_INSTAGRAM_ID",
    UPDATE_FULL_NAME_ERROR_FIELD: "UPDATE_FULL_NAME_ERROR_FIELD",
    UPDATE_MOBILE_ERROR_FIELD: "UPDATE_MOBILE_ERROR_FIELD",
    UPDATE_INSTAGRAM_ERROR_FIELD: "UPDATE_INSTAGRAM_ERROR_FIELD",

    SEND_QUES_DATA_TO_BACKEND: "SEND_QUES_DATA_TO_BACKEND",

    UPDATE_USER_NAME_ERROR_FIELD: "UPDATE_USER_NAME_ERROR_FIELD",
    UPDATE_PASSWORD_ERROR_FIELD: "UPDATE_PASSWORD_ERROR_FIELD",
    UPDATE_VALID_USER_NAME: "UPDATE_VALID_USER_NAME",
    UPDATE_VALID_PASSWPRD: "UPDATE_VALID_PASSWPRD",
    UPDATE_FORM_LOGIN_VALUE: "UPDATE_FORM_LOGIN_VALUE",
    GET_LOGIN_RESPONSE: "GET_LOGIN_RESPONSE",

    GET_ANSWERS_RESULT: "GET_ANSWERS_RESULT",

}


export const login = {
    UPDATE_FEACHING: "UPDATE_FEACHING",
    UPDATE_VALID_EMAIL_VALUE: "UPDATE_VALID_EMAIL_VALUE",
    UPDATE_EMAIL_ERROR_FIELD: "UPDATE_EMAIL_ERROR_FIELD",
    UPDATE_VALID_PASSWPRD: "UPDATE_VALID_PASSWPRD",
    UPDATE_PASSWORD_ERROR_FIELD: "UPDATE_PASSWORD_ERROR_FIELD",
    GET_LOGIN_RESPONSE: "GET_LOGIN_RESPONSE",
}

export const register = {
    UPDATE_FEACHING: "UPDATE_FEACHING",
    UPDATE_VALID_EMAIL_VALUE: "UPDATE_VALID_EMAIL_VALUE",
    UPDATE_EMAIL_ERROR_FIELD: "UPDATE_EMAIL_ERROR_FIELD",
    UPDATE_VALID_PASSWPRD: "UPDATE_VALID_PASSWPRD",
    UPDATE_PASSWORD_ERROR_FIELD: "UPDATE_PASSWORD_ERROR_FIELD",
    UPDATE_VALID_REPLACE_PASSWPRD: "UPDATE_VALID_REPLACE_PASSWPRD",
    UPDATE_REPLACE_PASSWORD_ERROR_FIELD: "UPDATE_REPLACE_PASSWORD_ERROR_FIELD",
    UPDATE_VALID_USER_TYPE: "UPDATE_VALID_USER_TYPE",
    UPDATE_USER_TYPE_ERROR_FIELD: "UPDATE_USER_TYPE_ERROR_FIELD",
    GET_REGISTER_RESPONSE: "GET_REGISTER_RESPONSE",
}
export const forgotPassword = {
    UPDATE_FEACHING: "UPDATE_FEACHING",
    UPDATE_CHANGE_PASSWORD_FEACHING: "UPDATE_CHANGE_PASSWORD_FEACHING",
    UPDATE_VALID_EMAIL_VALUE: "UPDATE_VALID_EMAIL_VALUE",
    UPDATE_EMAIL_ERROR_FIELD: "UPDATE_EMAIL_ERROR_FIELD",
    UPDATE_VALID_PASSWPRD: "UPDATE_VALID_PASSWPRD",
    UPDATE_PASSWORD_ERROR_FIELD: "UPDATE_PASSWORD_ERROR_FIELD",
    UPDATE_VALID_REPLACE_PASSWPRD: "UPDATE_VALID_REPLACE_PASSWPRD",
    UPDATE_REPLACE_PASSWORD_ERROR_FIELD: "UPDATE_REPLACE_PASSWORD_ERROR_FIELD",
    GET_FORGOT_PASSWORD_RESPONSE: "GET_FORGOT_PASSWORD_RESPONSE",
    GET_FORGOT_CHANGE_PASSWORD_RESPONSE: "GET_FORGOT_CHANGE_PASSWORD_RESPONSE",
}

export const dashboard = {
    UPDATE_FEACHING: "UPDATE_FEACHING",
    UPDATE_VALID_FIRST_NAME_VALUE: "UPDATE_VALID_FIRST_NAME_VALUE",
    UPDATE_FIRST_NAME_ERROR_FIELD: "UPDATE_FIRST_NAME_ERROR_FIELD",
    UPDATE_VALID_LAST_NAME_VALUE: "UPDATE_VALID_LAST_NAME_VALUE",
    UPDATE_LAST_NAME_ERROR_FIELD: "UPDATE_LAST_NAME_ERROR_FIELD",
    UPDATE_VALID_USER_GENDER: "UPDATE_VALID_USER_GENDER",
    UPDATE_USER_GENDER_ERROR_FIELD: "UPDATE_USER_GENDER_ERROR_FIELD",
    UPDATE_VALID_UNIVERSITY_ID_VALUE: "UPDATE_VALID_UNIVERSITY_ID_VALUE",
    UPDATE_UNIVERSITY_ID_ERROR_FIELD: "UPDATE_UNIVERSITY_ID_ERROR_FIELD",
    GET_COMPLETE_PROFILE_RESPONSE: "GET_COMPLETE_PROFILE_RESPONSE",
    GET_USER_INFO_RESPONSE: "GET_USER_INFO_RESPONSE",
    GET_UPDATE_PROFILE_RESPONSE: "GET_UPDATE_PROFILE_RESPONSE",
    GET_USER_LIST_DATA_RESPONSE: "GET_USER_LIST_DATA_RESPONSE",
    GET_USER_ACTIVE_RESPONSE: "GET_USER_ACTIVE_RESPONSE",
    DELETE_USER_RESPONSE_BY_ID: "DELETE_USER_RESPONSE_BY_ID",
    GET_LANGUAGES_LIST_DATA_RESPONSE: "GET_LANGUAGES_LIST_DATA_RESPONSE",
    UPDATE_VALID_AVAILABILITIES_VALUE: "UPDATE_VALID_AVAILABILITIES_VALUE",
    UPDATE_AVAILABILITIES_ERROR_FIELD: "UPDATE_AVAILABILITIES_ERROR_FIELD",
    UPDATE_VALID_LANGUAGE_VALUE: "UPDATE_VALID_LANGUAGE_VALUE",
    UPDATE_LANGUAGE_ERROR_FIELD: "UPDATE_LANGUAGE_ERROR_FIELD",
    UPDATE_VALID_COMMENT_VALUE: "UPDATE_VALID_COMMENT_VALUE",
    UPDATE_COMMENT_ERROR_FIELD: "UPDATE_COMMENT_ERROR_FIELD",
    UPDATE_VALID_PROGRAM_TIME_VALUE: "UPDATE_VALID_PROGRAM_TIME_VALUE",
    UPDATE_PROGRAM_TIME_ERROR_FIELD: "UPDATE_PROGRAM_TIME_ERROR_FIELD",
    GET_PROGRAM_REQUEST_DATA_RESPONSE: "GET_PROGRAM_REQUEST_DATA_RESPONSE",
    UPDATE_REQUEST_PROGRAM_LIST_RESPONSE: "UPDATE_REQUEST_PROGRAM_LIST_RESPONSE",
    UPDATE_TEACHER_LANGUAGE_REQUEST_RESPONSE: "UPDATE_TEACHER_LANGUAGE_REQUEST_RESPONSE",
    UPDATE_LANGUAGE_LIST_ID: "UPDATE_LANGUAGE_LIST_ID",
    UPDATE_LANGUAGE_LIST_ID_ERROR_FIELD: "UPDATE_LANGUAGE_LIST_ID_ERROR_FIELD",
    UPDATE_TEACHER_LANGUAGE_REQUEST_FORM_RESPONSE: "UPDATE_TEACHER_LANGUAGE_REQUEST_FORM_RESPONSE",
    UPDATE_TEACHER_PROGRAM_RESPONSE: "UPDATE_TEACHER_PROGRAM_RESPONSE",
    UPDATE_PROGRAM_STATUS_BY_ID: "UPDATE_PROGRAM_STATUS_BY_ID",
    GET_STUDY_LIST_DATA_RESPONSE: "GET_STUDY_LIST_DATA_RESPONSE",
    UPDATE_VALID_STUDY_VALUE: "UPDATE_VALID_STUDY_VALUE",
    UPDATE_STUDY_ERROR_FIELD: "UPDATE_STUDY_ERROR_FIELD",
}